data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/train_data.parquet"   # <- updated
  reference_path: "data/processed/train_data.parquet"   # <- same as processed
  current_path: "data/current/drifted_data.parquet"

model:
  target_column: "Is_Cancelled"
  random_state: 10
  test_size: 0.2
  n_estimators: 100
  max_depth: 10

mlflow:
  tracking_uri: "http://mlflow-server:5000"
  experiment_name: "uber-ride-prediction"
  model_name: "uber-ride-prediction-model"

thresholds:
  min_accuracy: 0.0
  min_f1_score: 0.0

deployment:
  api_endpoint: "http://localhost:8000"
  health_check_timeout: 30
