data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/features.parquet"
  reference_path: "data/reference.parquet"

model:
  target_column: "Is_Cancelled"
  random_state: 10
  test_size: 0.2
  n_estimators: 100
  max_depth: 10

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "uber-ride-prediction"

thresholds:
  min_accuracy: 0.8
  min_f1_score: 0.7
