data:
  raw_path: "data/raw/dataset.csv"
  ingested_path: "data/processed/ingested_data.parquet"
  processed_path: "data/processed/train_data.parquet"
  reference_path: "data/processed/train_data.parquet"
  current_path: "data/current/drifted_data.parquet"

features:
  feature_cols:
    - "avg_vtat"
    - "timestamp"

  numerical_cols:
    - "avg_vtat"

  datetime_cols:
    - "timestamp"

model:
  target_column: "is_cancelled"  # Note: lowercase as shown in your logs
  random_state: 10
  test_size: 0.2

mlflow:
  tracking_uri: "http://mlflow-server:5000"
  experiment_name: "uber-ride-prediction"
  model_name: "uber-ride-prediction-model"

thresholds:
  min_accuracy: 0.7

deployment:
  api_endpoint: "http://localhost:8000"
  health_check_timeout: 30
